### ISSUE TITLE
Refresh the database

### ISSUE THREAD

**Issue by bennyz** [bennyz/example-finder#17]
It should be possible to forcibly ignore the database, and the database should be refreshed periodically.

Since the details about repositories change over time (star count increases, latest commit updates, code changes) the data we save can go stale pretty quickly.

To resolve this a --no-cache flag should be introduced to avoid looking repos up in the database.
Also, a config value (probably using viper) should be introduced to mark stale database records, probably a week by default.

**Comment by matanshukry** [comment]
We might also want to introduce a flag to refresh the database manually, such as --refresh-db or w/e. 
WDYT?

**Comment by bennyz** [comment]
you're right, not sure why I didn't include this :\

**Comment by bennyz** [comment]
Now that I think about it, there might be a potential issue with #12 since this feature relies on using the database
